name: Integration testing with ansible-test-gh-action

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

# https://github.com/ansible-community/ansible-test-gh-action
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Perform integration testing with ansible-test
        uses: ansible-community/ansible-test-gh-action@release/v1
        with:
          testing-type: integration
      -
        name: Perform sanity testing with ansible-test
        uses: ansible-community/ansible-test-gh-action@release/v1
        with:
          testing-type: sanity
      -
        name: Perform unit testing with ansible-test
        uses: ansible-community/ansible-test-gh-action@release/v1
        with:
          testing-type: unit
